config/routes.rb
Rails.application.routes.draw do
  resources :projects
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root 'home#index'

  resources :projects, only: %i[index create new edit update destroy show]

  # devise_for :users, controllers: { sessions: 'users/sessions' }
end

app/models/project.rb
class Project < ApplicationRecord
  extend Enumerize

  belongs_to :user
  has_many :reviews

  enumerize :platform, in: %i[gitlab github]
  validates :link, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.build(project_params)


    if @project.save
      redirect_to :root, notice: t('projects.create.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET /projects/1
  def show
    # Авторизация
    @project = Project.find(params[:id])
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_path, status: :see_other, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:id, :name, :link, :auth_token, :platform)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.slim
= simple_form_for(@project) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.select :platform, collection: Project.platform.options
    = f.input :link
    = f.input :auth_token
    

  .form-actions
    = f.submit t('projects.links.save')

app/views/projects/_project.html.slim
div id="#{dom_id project}"

app/views/projects/edit.html.slim
h1 Editing project

== render "form", project: @project

br

div
  = link_to t('projects.links.back_to_projects'), projects_path

app/views/projects/index.html.slim
/ p style="color: green" = notice

h1 = t('projects.all_projects')

.projects_container
  - @projects.each do |project|
    = link_to project.name, project_path(project)


= link_to t("projects.new_project"), new_project_path

app/views/projects/new.html.slim
h1 New project

== render "form", project: @project

br

div
  = link_to t('projects.links.back_to_projects'), projects_path

app/views/projects/show.html.slim
h1 = @project.name