config/routes.rb
Rails.application.routes.draw do
  resources :projects
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root 'home#index'

  resources :projects, only: %i[index create new edit update destroy show]

  # devise_for :users, controllers: { sessions: 'users/sessions' }
end

app/views/layouts/_nav.html.slim
.container
  .d-flex.flex-wrap.align-items-center.justify-content-between.justify-content-md-between.py-3.mb-4.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      nav_menu_item.me-2 = link_to t('navigation.links.projects'), projects_path, class: 'nav-link'
      - if user_signed_in?
        .collapse.navbar-collapse
          ul.nav.nav-pills.flex-grow-1.navbar-nav.me-auto
            / TODO: Подсветка выделенных элементов меню
            nav_menu_item.me-2 = link_to t('navigation.links.statistics'), root_path, class: 'nav-link'
    ul.nav.nav-pills
      - if user_signed_in?
        nav_menu_item.me-2.nav-link.text-dark = t('navigation.hello', user_name: current_user.email)
        nav_menu_item.me-2 = button_to t('navigation.links.log_out'), destroy_user_session_path, method: :delete, class: 'nav-link text-dark'
      - else
        nav_menu_item.me-2 = button_to t('navigation.links.log_in'), new_user_session_path, data: { turbo: false },
          method: :post, class: 'nav-link text-dark'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = content_for(:title) || t('navigation.title')
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    meta[name="apple-mobile-web-app-capable" content="yes"]
    meta[name="mobile-web-app-capable" content="yes"]
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    - # Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!)
    - #= tag.link rel: "manifest", href: pwa_manifest_path(format: :json)
    link[rel="icon" href="/icon.png" type="image/png"]
    link[rel="icon" href="/icon.svg" type="image/svg+xml"]
    link[rel="apple-touch-icon" href="/icon.png"]
    - # Includes all stylesheet files in app/assets/stylesheets
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_importmap_tags
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
  body
    = render 'layouts/nav'
    .container
      .my-4
        - if flash[:notice]
          .alert.alert-info = flash[:notice]
        - if flash[:alert]
          .alert.alert-danger = flash[:alert]
      = yield